version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=okpos.settings
      - DEBUG=1
      - ALLOWED_HOSTS=*
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn okpos.wsgi:application --bind 0.0.0.0:8000"